# Generated by Django 2.2.14 on 2021-03-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='AMS', max_length=20),
        ),
    ]
